# Data Flow Configuration for Claude Code Optimizer
# Simplified ingestion pipeline configuration

# Claude Code monitoring
claude_data_dir: "~/.claude"
watch_patterns:
  - "**/*.jsonl"
  - "**/requests.log"
  - "**/conversations/*.json"

# Database connections
supabase:
  url: ${SUPABASE_URL}
  anon_key: ${SUPABASE_ANON_KEY}
  connection_pool_size: 10
  timeout_seconds: 30
  retry_attempts: 3

sqlite:
  path: "claude_analytics.db"
  connection_timeout: 30
  journal_mode: "WAL"
  synchronous: "NORMAL"
  cache_size: 64000  # 64MB cache

# Processing configuration
processing:
  batch_size: 100
  worker_count: 2
  queue_max_size: 1000
  processing_timeout: 30
  chunk_size: 8192
  max_memory_usage_mb: 200

# Error handling
error_handling:
  max_retry_attempts: 3
  retry_base_delay: 1.0
  retry_max_delay: 60.0
  circuit_breaker_threshold: 5
  circuit_breaker_timeout: 60
  error_rate_threshold: 0.1
  critical_error_threshold: 5
  graceful_degradation: true

# Performance monitoring
monitoring:
  enable_system_monitoring: true
  enable_pipeline_monitoring: true
  enable_database_monitoring: true
  monitoring_interval: 10
  resource_check_interval: 30
  alert_check_interval: 60
  metrics_retention_hours: 168
  performance_log_level: "INFO"

# Performance thresholds
thresholds:
  cpu_usage:
    warning: 70
    critical: 90
  memory_usage:
    warning: 80
    critical: 95
  disk_io_rate:
    warning: 100
    critical: 500
  network_io_rate:
    warning: 50
    critical: 200
  processing_latency:
    warning: 100
    critical: 500
  error_rate:
    warning: 0.05
    critical: 0.1
  queue_depth:
    warning: 100
    critical: 500
  connection_count:
    warning: 50
    critical: 100
  response_time:
    warning: 1000
    critical: 5000

# Data validation
validation:
  auto_correct: true
  strict_mode: false
  max_content_length: 10000
  required_fields:
    session:
      - "session_id"
      - "timestamp"
    message:
      - "role"
      - "content"
    tool:
      - "tool_name"
  field_patterns:
    session_id: "^[a-zA-Z0-9_-]+$"
    email: "^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$"
    uuid: "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$"
  value_ranges:
    tokens:
      min: 0
      max: 1000000
    cost:
      min: 0.0
      max: 1000.0
    duration_minutes:
      min: 0.0
      max: 1440.0
  known_models:
    - "claude-3-5-sonnet-20241022"
    - "claude-3-5-haiku-20241022"
    - "claude-3-opus-20240229"
    - "claude-3-sonnet-20240229"
    - "claude-3-haiku-20240307"
    - "gpt-4"
    - "gpt-4-turbo"
    - "gpt-3.5-turbo"
    - "gpt-4o"
    - "gpt-4o-mini"
  known_tools:
    - "str_replace_editor"
    - "bash"
    - "computer"
    - "read_file"
    - "write_file"
    - "list_files"
    - "search"
    - "grep"
    - "find"
    - "git"
    - "python"
    - "npm"
    - "curl"

# Health checks
health_checks:
  enabled: true
  interval: 60
  endpoints:
    - name: "supabase_connection"
      type: "database"
      timeout: 10
    - name: "sqlite_connection"
      type: "database"
      timeout: 5
    - name: "file_watcher"
      type: "service"
      timeout: 5
    - name: "processing_queue"
      type: "queue"
      timeout: 5

# Alerting
alerts:
  enabled: true
  cooldown_seconds: 300
  notification_methods:
    - "log"
    - "webhook"
  webhook:
    url: ${ALERT_WEBHOOK_URL}
    timeout: 10
    retry_attempts: 3
  alert_rules:
    - name: "high_cpu_usage"
      condition: "cpu_usage > 90"
      severity: "critical"
      message: "CPU usage is critically high"
    - name: "high_memory_usage"
      condition: "memory_usage > 95"
      severity: "critical"
      message: "Memory usage is critically high"
    - name: "high_error_rate"
      condition: "error_rate > 0.1"
      severity: "critical"
      message: "Error rate is critically high"
    - name: "queue_backup"
      condition: "queue_depth > 500"
      severity: "warning"
      message: "Processing queue is backing up"
    - name: "slow_processing"
      condition: "processing_latency > 1000"
      severity: "warning"
      message: "Processing latency is high"

# Optimization
optimization:
  auto_scaling: true
  target_cpu_usage: 60
  target_memory_usage: 70
  scale_up_threshold: 80
  scale_down_threshold: 40
  min_workers: 1
  max_workers: 8
  cache_optimization: true
  batch_optimization: true
  connection_pooling: true

# Security
security:
  encrypt_sensitive_data: true
  sanitize_logs: true
  secure_connections: true
  rate_limiting: true
  api_key_rotation: false

# Backup and recovery
backup:
  enabled: true
  interval_hours: 6
  retention_days: 30
  compress: true
  verify_integrity: true
  backup_location: "backups/"

# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_rotation: true
  max_file_size_mb: 50
  backup_count: 5
  structured_logging: true
  log_to_file: true
  log_to_console: true

# Development settings
development:
  debug_mode: false
  verbose_logging: false
  test_mode: false
  mock_external_services: false
  enable_profiling: false
  
# Feature flags
features:
  enable_real_time_sync: true
  enable_cache_warming: true
  enable_predictive_scaling: false
  enable_advanced_analytics: true
  enable_ml_optimization: false
  enable_webhook_notifications: true