# Performance Tuning Configuration
# Settings for optimizing system performance

performance_settings:
  # CPU and Processing
  cpu:
    max_workers: 4
    worker_timeout: 30
    batch_size: 100
    processing_interval: 0.1
  
  # Memory Management
  memory:
    cache_size_mb: 256
    buffer_size: 1024
    gc_threshold: 0.8
    cleanup_interval: 300
  
  # Database and Storage
  database:
    connection_pool_size: 10
    query_timeout: 30
    batch_insert_size: 1000
    index_rebuild_interval: 3600
  
  # Network and API
  network:
    request_timeout: 10
    max_retries: 3
    connection_keepalive: true
    rate_limit_per_second: 100
  
  # Monitoring and Metrics
  monitoring:
    metrics_collection_interval: 60
    performance_log_level: "INFO"
    alert_thresholds:
      cpu_percent: 80
      memory_percent: 85
      response_time_ms: 1000
  
  # Optimization Features
  optimization:
    enable_caching: true
    enable_compression: true
    enable_async_processing: true
    enable_lazy_loading: true
    
  # Resource Limits
  limits:
    max_concurrent_requests: 50
    max_file_size_mb: 100
    max_session_duration: 3600
    max_log_file_size_mb: 50

# Environment-specific overrides
environments:
  development:
    performance_settings:
      monitoring:
        metrics_collection_interval: 30
        performance_log_level: "DEBUG"
  
  production:
    performance_settings:
      cpu:
        max_workers: 8
      memory:
        cache_size_mb: 512
      limits:
        max_concurrent_requests: 100